name = input("Enter your name: ")
college = input("Enter your college: ")
branch = input("Enter your branch: ")
year = input("Enter your year: ")

print("\n----- Student Details -----")
print("Name:", name)
print("College:", college)
print("Branch:", branch)
print("Year:", year)