from io import BytesIO
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT


def generate_cover_docx(markdown_text: str):
    """
    Convert the AI-generated cover letter (Markdown/text)
    into a professionally formatted DOCX file.
    """

    doc = Document()

    # =====================================================
    # Title
    # =====================================================

    title = doc.add_heading("AI Resume Copilot", level=1)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    subtitle = doc.add_heading("Professional Cover Letter", level=2)
    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    doc.add_paragraph()

    # =====================================================
    # Body
    # =====================================================

    lines = markdown_text.splitlines()

    for line in lines:

        line = line.strip()

        if not line:
            continue

        # Heading 1
        if line.startswith("# "):

            heading = doc.add_heading(
                line.replace("# ", ""),
                level=1
            )

            heading.runs[0].font.size = Pt(18)

        # Heading 2
        elif line.startswith("## "):

            heading = doc.add_heading(
                line.replace("## ", ""),
                level=2
            )

            heading.runs[0].font.size = Pt(15)

        # Bullet
        elif line.startswith("- "):

            paragraph = doc.add_paragraph(
                style="List Bullet"
            )

            paragraph.add_run(
                line.replace("- ", "")
            )

        # Normal Paragraph
        else:

            paragraph = doc.add_paragraph()

            run = paragraph.add_run(line)

            run.font.size = Pt(11)

    # =====================================================
    # Footer
    # =====================================================

    doc.add_paragraph()

    footer = doc.add_paragraph()

    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    footer_run = footer.add_run(
        "Generated by AI Resume Copilot"
    )

    footer_run.italic = True
    footer_run.font.size = Pt(10)

    # =====================================================
    # Save
    # =====================================================

    buffer = BytesIO()

    doc.save(buffer)

    buffer.seek(0)

    return buffer.getvalue()