from io import BytesIO

from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.shared import Pt


def generate_interview_docx(report: dict):
    """
    Generate a DOCX interview preparation guide.
    """

    document = Document()

    # =====================================================
    # Title
    # =====================================================

    title = document.add_heading(
        "AI Resume Copilot",
        level=1,
    )

    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    subtitle = document.add_heading(
        "Interview Preparation Guide",
        level=2,
    )

    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    document.add_paragraph()

    # =====================================================
    # Job Role
    # =====================================================

    document.add_heading("Target Job Role", level=2)

    document.add_paragraph(
        report["job_role"]
    )

    document.add_heading("Difficulty", level=2)

    document.add_paragraph(
        report["difficulty"]
    )

    # =====================================================
    # Technical Questions
    # =====================================================

    document.add_heading(
        "Technical Questions",
        level=2,
    )

    for i, item in enumerate(
        report["technical_questions"],
        start=1,
    ):

        p = document.add_paragraph()

        p.add_run(
            f"{i}. {item['question']}\n"
        ).bold = True

        p.add_run(
            f"Suggested Answer:\n{item['answer']}"
        )

    # =====================================================
    # HR Questions
    # =====================================================

    document.add_heading(
        "HR Questions",
        level=2,
    )

    for i, item in enumerate(
        report["hr_questions"],
        start=1,
    ):

        p = document.add_paragraph()

        p.add_run(
            f"{i}. {item['question']}\n"
        ).bold = True

        p.add_run(
            f"Suggested Answer:\n{item['answer']}"
        )

    # =====================================================
    # Behavioral Questions
    # =====================================================

    document.add_heading(
        "Behavioral Questions",
        level=2,
    )

    for i, item in enumerate(
        report["behavioral_questions"],
        start=1,
    ):

        p = document.add_paragraph()

        p.add_run(
            f"{i}. {item['question']}\n"
        ).bold = True

        p.add_run(
            f"Suggested Answer:\n{item['answer']}"
        )

    # =====================================================
    # Tips
    # =====================================================

    document.add_heading(
        "Interview Tips",
        level=2,
    )

    for tip in report["tips"]:

        document.add_paragraph(
            tip,
            style="List Bullet",
        )

    # =====================================================
    # Footer
    # =====================================================

    footer = document.add_paragraph()

    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    run = footer.add_run(
        "\nGenerated by AI Resume Copilot"
    )

    run.italic = True
    run.font.size = Pt(10)

    # =====================================================
    # Save
    # =====================================================

    buffer = BytesIO()

    document.save(buffer)

    buffer.seek(0)

    return buffer.getvalue()